apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: harbor
  namespace: argo-cd
  annotations:
    argocd.argoproj.io/sync-wave: "2"  
spec:
  destination:
    namespace: harbor
    server: https://kubernetes.default.svc
  project: argocd
  source:
    repoURL: 'https://github.com/ioaiaaii/local-cluster.git'
    path: meta-charts/harbor
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
