---
- name: restart crio
  service:
    name: crio
    state: restarted

- name: restart kubelet
  service:
    name: kubelet
    state: restarted

- name: restart containerd
  service:
    name: containerd
    state: restarted

- name: restart containerd
  service:
    name: docker
    state: restarted

- name: docker status
  service: 
    name: docker 
    state: started