sysctl_config:
  net.bridge.bridge-nf-call-iptables: 1
  net.bridge.bridge-nf-call-ip6tables: 1
  net.ipv4.ip_forward: 1

#https://github.com/cri-o/cri-o/issues/5899
# crio_version: "{{ kubernetes_version | regex_replace('^([0-9]+)\\.([0-9]+)\\.[0-9]+', '\\1.\\2') }}"
crio_version: "1.23"