- name: Add bitnmani Helm repo
  kubernetes.core.helm_repository:
    name: bitnmani
    repo_url: https://charts.bitnami.com/bitnami

- name: Install MetalLB
  kubernetes.core.helm:
    name: metallb
    chart_ref: bitnmani/metallb
    chart_version: "{{ metallb_release }}"
    create_namespace: yes
    release_namespace: metal-lb
    update_repo_cache: true
    wait: true
    #timeout to ensure that admission webhooks are up for the next step
    timeout: "10m"

- name: Upgrade MetalLB
  kubernetes.core.helm:
    name: metallb
    chart_ref: bitnmani/metallb
    chart_version: "{{ metallb_release }}"
    create_namespace: yes
    release_namespace: metal-lb
    release_values: "{{ metallb_helm_values }}"
    wait: true
