apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack-crds
  namespace: argo-cd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  destination:
    namespace: kube-prometheus-stack
    server: 'https://kubernetes.default.svc'
  project: argocd
  source:
    repoURL: 'https://github.com/ioaiaaii/local-cluster.git'
    path: meta-charts/kube-prometheus-stack/crds
    targetRevision: HEAD
    directory:
      recurse: true
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - Replace=true
      - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true