apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argo-cd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  destination:
    namespace: kube-prometheus-stack
    server: https://kubernetes.default.svc
  project: argocd
  source:
    repoURL: 'https://github.com/ioaiaaii/local-cluster.git'
    path: meta-charts/kube-prometheus-stack
    targetRevision: HEAD
    helm:
      skipCrds: true
      valueFiles:
        - values.yaml
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
