#cloud-config
package_update: true
package_upgrade: true
packages:
  - unzip
  - software-properties-common
  - gnupg2
  - curl

write_files:
  - path: /etc/syctl.conf
    content: |
      net.ipv4.ip_forward=1

groups:
  - docker

system_info:
  default_user:
    groups: [docker]

runcmd: 
 - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
 - curl -fsSLo /usr/share/keyrings/kubernetes-archive-keyring.gpg https://packages.cloud.google.com/apt/doc/apt-key.gpg
 - echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
 - echo "deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee /etc/apt/sources.list.d/kubernetes.list
 - wget -qO - terraform.gpg https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/terraform-archive-keyring.gpg
 - echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/terraform-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" > /etc/apt/sources.list.d/terraform.list
 - curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.14.0/kind-linux-amd64 && chmod +x ./kind && sudo mv ./kind /usr/sbin/
 - curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
 - apt-get update -y 
 - apt-get install -y docker-ce docker-ce-cli containerd.io kubectl terraform
 - sysctl --system

final_message: "The system is finally up, after $UPTIME seconds"